plugins {
    id 'java-library'
    id('io.qameta.allure') version '4.0.2'
}

group = 'guru.qa_homework'
version = '1.0-SNAPSHOT'

allure {
    report {
        version.set("2.34.0")
    }
    adapter {
        aspectjWeaver.set(true)
        frameworks {
            junit5 {
                adapterVersion.set("2.34.0")
            }
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation (
            "com.codeborne:selenide:7.16.2",
            "org.junit.jupiter:junit-jupiter:5.14.3",
            "io.qameta.allure:allure-junit5:2.34.0",
            'org.slf4j:slf4j-simple:2.0.18',
            'commons-io:commons-io:2.22.0',
            'org.assertj:assertj-core:3.27.7',
            'com.codeborne:pdf-test:2.1.0',
            'io.qameta.allure:allure-selenide:2.34.0',
            'org.aeonbits.owner:owner:1.0.4',
            'tools.jackson.core:jackson-databind:3.1.0',
            "io.rest-assured:rest-assured:6.0.0",
            "io.rest-assured:json-schema-validator:6.0.0",
            "io.qameta.allure:allure-rest-assured:2.32.0"
    )
    testRuntimeOnly(
            "org.junit.platform:junit-platform-launcher"
    )
}

test {
    def tags = System.getProperty('includeTags')
    useJUnitPlatform {
        if (tags) {
            includeTags tags
        }
    }
    systemProperties(System.getProperties())
}

tasks.withType(Test) {
    testLogging {
        lifecycle {
            events "started", "skipped", "failed", "standard_error", "standard_out"
            exceptionFormat "short"
        }
    }
}